server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: C:/Users/Drissi houcem eddine/Desktop/Repo-Locale/ms-config/src/main/resources/microConfig
  application:
    name: ms-config
